on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          command: manifest
          monorepo-tags: true

      - name: Release executed
        run: echo '${{toJSON(steps.release)}}'

      - if: ${{ steps.release.outputs.releases_created }}
        name: Release created
        run: echo '${{toJSON(steps.release.outputs)}}'

      # - if: ${{ steps.release.outputs.releases_created }}
      #   uses: actions/checkout@v3

      # - if: ${{ steps.release.outputs.releases_created }}
      #   uses: actions/setup-node@v3
      #     with:
      #       cache: 'yarn'
      #       node-version: 16
      #       registry-url: 'https://registry.npmjs.org'
      # - if: ${{ steps.release.outputs.releases_created }}
      #   run: yarn install --frozen-lockfile
